include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    [
      build/**,
      lib/**.freezed.dart,
      lib/**.g.dart,
      lib/**.generated.dart,
      lib/**.gr.dart,
      lib/**.mocks.dart,
    ]
  errors:
    constant_pattern_never_matches_value_type: ignore
    duplicate_ignore: ignore
    invalid_annotation_target: ignore
    # If you’re using Flutter widgets without keys intentionally, keep ignore
    # Otherwise, remove this to enforce best practice
    use_key_in_widget_constructors: ignore

linter:
  rules:
    # ✅ Style / readability
    - always_use_package_imports
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cascade_invocations
    - prefer_final_locals
    - prefer_final_in_for_each
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - sort_child_properties_last
    - unnecessary_breaks
    - use_full_hex_values_for_flutter_colors
    - use_string_buffers
    - missing_whitespace_between_adjacent_strings
    - join_return_with_assignment

    # ✅ Error prevention
    - cancel_subscriptions
    - close_sinks
    - discarded_futures
    - no_runtimeType_toString
    - literal_only_boolean_expressions
    - use_build_context_synchronously
    - unsafe_html
    - avoid_dynamic_calls

    # ✅ Dart 3 pattern matching / modern features
    - invalid_case_patterns
    - exhaustive_cases
    - prefer_expression_function_bodies

    # ✅ Async safety
    - avoid_types_on_closure_parameters
    - avoid_renaming_method_parameters
