targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/features/**.dart
        options:
          from_json: true
          to_json: true
          copy_with: true
          equal: true
          map: true
          when: true
          immutable: true
          add_diagnostics: true
          make_sealed: true

      json_serializable:
        generate_for:
          - lib/features/**.dart
        options:
          explicit_to_json: true
          include_if_null: true
          field_rename: none
          checked: true
          disallow_unrecognized_keys: false
          ignore_unannotated: false
